import { join } from "node:path";

/**
 * `data/review/` layout — implementation.md section 4.3 ("data/review/ —
 * human review decisions") and section 5.11's intro ("Review data must be
 * separate from generated observations so reruns cannot overwrite
 * editorial work").
 *
 * Structural difference from every other pipeline stage (documented
 * choice, per this session's brief): `data/raw/{inventory,crawl,analysis}/`
 * are all keyed by `<runId>/` and are wholly regenerated by their producing
 * command. `data/review/` is NOT keyed by runId at the top level — it is
 * keyed by the thing a human decided about (`findingId`, `artifactId`,
 * `comparisonId`), because review decisions are hand-authored, individually
 * diffable editorial work that must survive an unrelated `analyze`/`crawl`
 * rerun untouched. A `ReviewDecision` file's own `findingId` still lets a
 * later validation pass tell which run(s) it applies to (a finding id is
 * only ever produced by one run, per `materialize.ts`'s id scheme), so
 * nothing is lost by not nesting under `<runId>/`.
 *
 * Three parallel one-file-per-record subdirectories, each JSON, named by
 * the record's own key:
 *   - decisions/<findingId>.json              — ReviewDecision (§5.11)
 *   - evidence-privacy/<artifactId>.json       — privacy-review overlay
 *     (documented local convention, see evidence-privacy-store.ts)
 *   - overlap-comparisons/<comparisonId>.json  — PortalOverlapComparison
 *     (§5.9), hand-authored per section 7.6's manual-review-first workflow
 *
 * File-per-record was chosen over one shared JSONL/array file because
 * section 5.11's own rationale ("so reruns cannot overwrite editorial
 * work") is best served by records a human can open, edit, and diff
 * individually in Git — a single shared file would make concurrent manual
 * edits by different reviewers collide and would make `git diff` noisier
 * for a one-finding change.
 */
export interface ReviewPaths {
  reviewDir: string;
  decisionsDir: string;
  evidencePrivacyDir: string;
  overlapComparisonsDir: string;
  publishedDir: string;
}

export function reviewPaths(repoRoot: string): ReviewPaths {
  const reviewDir = join(repoRoot, "data", "review");
  return {
    reviewDir,
    decisionsDir: join(reviewDir, "decisions"),
    evidencePrivacyDir: join(reviewDir, "evidence-privacy"),
    overlapComparisonsDir: join(reviewDir, "overlap-comparisons"),
    publishedDir: join(repoRoot, "data", "published"),
  };
}
